/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as InquireRouteImport } from './routes/inquire'
import { Route as DiasporaRouteImport } from './routes/diaspora'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookVisitRouteImport } from './routes/book-visit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DocumentReceiptIdRouteImport } from './routes/document.receipt.$id'
import { Route as DocumentAgreementIdRouteImport } from './routes/document.agreement.$id'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const InquireRoute = InquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const DiasporaRoute = DiasporaRouteImport.update({
  id: '/diaspora',
  path: '/diaspora',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVisitRoute = BookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentReceiptIdRoute = DocumentReceiptIdRouteImport.update({
  id: '/document/receipt/$id',
  path: '/document/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentAgreementIdRoute = DocumentAgreementIdRouteImport.update({
  id: '/document/agreement/$id',
  path: '/document/agreement/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/document/agreement/$id': typeof DocumentAgreementIdRoute
  '/document/receipt/$id': typeof DocumentReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/document/agreement/$id': typeof DocumentAgreementIdRoute
  '/document/receipt/$id': typeof DocumentReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/document/agreement/$id': typeof DocumentAgreementIdRoute
  '/document/receipt/$id': typeof DocumentReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book-visit'
    | '/contact'
    | '/diaspora'
    | '/inquire'
    | '/locations'
    | '/partner'
    | '/payment'
    | '/portal'
    | '/privacy'
    | '/thank-you'
    | '/blog/$slug'
    | '/properties/$slug'
    | '/blog/'
    | '/properties/'
    | '/document/agreement/$id'
    | '/document/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/book-visit'
    | '/contact'
    | '/diaspora'
    | '/inquire'
    | '/locations'
    | '/partner'
    | '/payment'
    | '/portal'
    | '/privacy'
    | '/thank-you'
    | '/blog/$slug'
    | '/properties/$slug'
    | '/blog'
    | '/properties'
    | '/document/agreement/$id'
    | '/document/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book-visit'
    | '/contact'
    | '/diaspora'
    | '/inquire'
    | '/locations'
    | '/partner'
    | '/payment'
    | '/portal'
    | '/privacy'
    | '/thank-you'
    | '/blog/$slug'
    | '/properties/$slug'
    | '/blog/'
    | '/properties/'
    | '/document/agreement/$id'
    | '/document/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookVisitRoute: typeof BookVisitRoute
  ContactRoute: typeof ContactRoute
  DiasporaRoute: typeof DiasporaRoute
  InquireRoute: typeof InquireRoute
  LocationsRoute: typeof LocationsRoute
  PartnerRoute: typeof PartnerRoute
  PaymentRoute: typeof PaymentRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ThankYouRoute: typeof ThankYouRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  DocumentAgreementIdRoute: typeof DocumentAgreementIdRoute
  DocumentReceiptIdRoute: typeof DocumentReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquire': {
      id: '/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof InquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaspora': {
      id: '/diaspora'
      path: '/diaspora'
      fullPath: '/diaspora'
      preLoaderRoute: typeof DiasporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-visit': {
      id: '/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof BookVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/receipt/$id': {
      id: '/document/receipt/$id'
      path: '/document/receipt/$id'
      fullPath: '/document/receipt/$id'
      preLoaderRoute: typeof DocumentReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/agreement/$id': {
      id: '/document/agreement/$id'
      path: '/document/agreement/$id'
      fullPath: '/document/agreement/$id'
      preLoaderRoute: typeof DocumentAgreementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookVisitRoute: BookVisitRoute,
  ContactRoute: ContactRoute,
  DiasporaRoute: DiasporaRoute,
  InquireRoute: InquireRoute,
  LocationsRoute: LocationsRoute,
  PartnerRoute: PartnerRoute,
  PaymentRoute: PaymentRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  ThankYouRoute: ThankYouRoute,
  BlogSlugRoute: BlogSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  DocumentAgreementIdRoute: DocumentAgreementIdRoute,
  DocumentReceiptIdRoute: DocumentReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
