/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as InquireRouteImport } from './routes/inquire'
import { Route as DiasporaRouteImport } from './routes/diaspora'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookVisitRouteImport } from './routes/book-visit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTelephonyRouteImport } from './routes/admin.telephony'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSiteContentRouteImport } from './routes/admin.site-content'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReferralsTestimonialsRouteImport } from './routes/admin.referrals-testimonials'
import { Route as AdminPropertyMatchingRouteImport } from './routes/admin.property-matching'
import { Route as AdminPlotsRouteImport } from './routes/admin.plots'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMeetingsRouteImport } from './routes/admin.meetings'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminInstallmentsRouteImport } from './routes/admin.installments'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminGoalsRouteImport } from './routes/admin.goals'
import { Route as AdminFieldModeRouteImport } from './routes/admin.field-mode'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminDataGovernanceRouteImport } from './routes/admin.data-governance'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as DocumentReceiptIdRouteImport } from './routes/document.receipt.$id'
import { Route as DocumentOfferIdRouteImport } from './routes/document.offer.$id'
import { Route as DocumentAgreementIdRouteImport } from './routes/document.agreement.$id'
import { Route as AdminPlotsPlotIdRouteImport } from './routes/admin.plots.$plotId'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const InquireRoute = InquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const DiasporaRoute = DiasporaRouteImport.update({
  id: '/diaspora',
  path: '/diaspora',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVisitRoute = BookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTelephonyRoute = AdminTelephonyRouteImport.update({
  id: '/telephony',
  path: '/telephony',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsTestimonialsRoute =
  AdminReferralsTestimonialsRouteImport.update({
    id: '/referrals-testimonials',
    path: '/referrals-testimonials',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPropertyMatchingRoute = AdminPropertyMatchingRouteImport.update({
  id: '/property-matching',
  path: '/property-matching',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlotsRoute = AdminPlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeetingsRoute = AdminMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstallmentsRoute = AdminInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoalsRoute = AdminGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFieldModeRoute = AdminFieldModeRouteImport.update({
  id: '/field-mode',
  path: '/field-mode',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataGovernanceRoute = AdminDataGovernanceRouteImport.update({
  id: '/data-governance',
  path: '/data-governance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const DocumentReceiptIdRoute = DocumentReceiptIdRouteImport.update({
  id: '/document/receipt/$id',
  path: '/document/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentOfferIdRoute = DocumentOfferIdRouteImport.update({
  id: '/document/offer/$id',
  path: '/document/offer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentAgreementIdRoute = DocumentAgreementIdRouteImport.update({
  id: '/document/agreement/$id',
  path: '/document/agreement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlotsPlotIdRoute = AdminPlotsPlotIdRouteImport.update({
  id: '/$plotId',
  path: '/$plotId',
  getParentRoute: () => AdminPlotsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/data-governance': typeof AdminDataGovernanceRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/field-mode': typeof AdminFieldModeRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plots': typeof AdminPlotsRouteWithChildren
  '/admin/property-matching': typeof AdminPropertyMatchingRoute
  '/admin/referrals-testimonials': typeof AdminReferralsTestimonialsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/telephony': typeof AdminTelephonyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/plots/$plotId': typeof AdminPlotsPlotIdRoute
  '/document/agreement/$id': typeof DocumentAgreementIdRoute
  '/document/offer/$id': typeof DocumentOfferIdRoute
  '/document/receipt/$id': typeof DocumentReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/data-governance': typeof AdminDataGovernanceRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/field-mode': typeof AdminFieldModeRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plots': typeof AdminPlotsRouteWithChildren
  '/admin/property-matching': typeof AdminPropertyMatchingRoute
  '/admin/referrals-testimonials': typeof AdminReferralsTestimonialsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/telephony': typeof AdminTelephonyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/plots/$plotId': typeof AdminPlotsPlotIdRoute
  '/document/agreement/$id': typeof DocumentAgreementIdRoute
  '/document/offer/$id': typeof DocumentOfferIdRoute
  '/document/receipt/$id': typeof DocumentReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/diaspora': typeof DiasporaRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/data-governance': typeof AdminDataGovernanceRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/field-mode': typeof AdminFieldModeRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plots': typeof AdminPlotsRouteWithChildren
  '/admin/property-matching': typeof AdminPropertyMatchingRoute
  '/admin/referrals-testimonials': typeof AdminReferralsTestimonialsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/telephony': typeof AdminTelephonyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/plots/$plotId': typeof AdminPlotsPlotIdRoute
  '/document/agreement/$id': typeof DocumentAgreementIdRoute
  '/document/offer/$id': typeof DocumentOfferIdRoute
  '/document/receipt/$id': typeof DocumentReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book-visit'
    | '/contact'
    | '/diaspora'
    | '/inquire'
    | '/locations'
    | '/partner'
    | '/payment'
    | '/portal'
    | '/privacy'
    | '/terms'
    | '/thank-you'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/contacts'
    | '/admin/data-governance'
    | '/admin/deals'
    | '/admin/documents'
    | '/admin/field-mode'
    | '/admin/goals'
    | '/admin/inquiries'
    | '/admin/installments'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/meetings'
    | '/admin/notifications'
    | '/admin/plots'
    | '/admin/property-matching'
    | '/admin/referrals-testimonials'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/staff'
    | '/admin/tasks'
    | '/admin/telephony'
    | '/blog/$slug'
    | '/properties/$slug'
    | '/admin/'
    | '/blog/'
    | '/properties/'
    | '/admin/plots/$plotId'
    | '/document/agreement/$id'
    | '/document/offer/$id'
    | '/document/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-visit'
    | '/contact'
    | '/diaspora'
    | '/inquire'
    | '/locations'
    | '/partner'
    | '/payment'
    | '/portal'
    | '/privacy'
    | '/terms'
    | '/thank-you'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/contacts'
    | '/admin/data-governance'
    | '/admin/deals'
    | '/admin/documents'
    | '/admin/field-mode'
    | '/admin/goals'
    | '/admin/inquiries'
    | '/admin/installments'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/meetings'
    | '/admin/notifications'
    | '/admin/plots'
    | '/admin/property-matching'
    | '/admin/referrals-testimonials'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/staff'
    | '/admin/tasks'
    | '/admin/telephony'
    | '/blog/$slug'
    | '/properties/$slug'
    | '/admin'
    | '/blog'
    | '/properties'
    | '/admin/plots/$plotId'
    | '/document/agreement/$id'
    | '/document/offer/$id'
    | '/document/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book-visit'
    | '/contact'
    | '/diaspora'
    | '/inquire'
    | '/locations'
    | '/partner'
    | '/payment'
    | '/portal'
    | '/privacy'
    | '/terms'
    | '/thank-you'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/contacts'
    | '/admin/data-governance'
    | '/admin/deals'
    | '/admin/documents'
    | '/admin/field-mode'
    | '/admin/goals'
    | '/admin/inquiries'
    | '/admin/installments'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/meetings'
    | '/admin/notifications'
    | '/admin/plots'
    | '/admin/property-matching'
    | '/admin/referrals-testimonials'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/staff'
    | '/admin/tasks'
    | '/admin/telephony'
    | '/blog/$slug'
    | '/properties/$slug'
    | '/admin/'
    | '/blog/'
    | '/properties/'
    | '/admin/plots/$plotId'
    | '/document/agreement/$id'
    | '/document/offer/$id'
    | '/document/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookVisitRoute: typeof BookVisitRoute
  ContactRoute: typeof ContactRoute
  DiasporaRoute: typeof DiasporaRoute
  InquireRoute: typeof InquireRoute
  LocationsRoute: typeof LocationsRoute
  PartnerRoute: typeof PartnerRoute
  PaymentRoute: typeof PaymentRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  DocumentAgreementIdRoute: typeof DocumentAgreementIdRoute
  DocumentOfferIdRoute: typeof DocumentOfferIdRoute
  DocumentReceiptIdRoute: typeof DocumentReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquire': {
      id: '/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof InquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaspora': {
      id: '/diaspora'
      path: '/diaspora'
      fullPath: '/diaspora'
      preLoaderRoute: typeof DiasporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-visit': {
      id: '/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof BookVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/telephony': {
      id: '/admin/telephony'
      path: '/telephony'
      fullPath: '/admin/telephony'
      preLoaderRoute: typeof AdminTelephonyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-content': {
      id: '/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals-testimonials': {
      id: '/admin/referrals-testimonials'
      path: '/referrals-testimonials'
      fullPath: '/admin/referrals-testimonials'
      preLoaderRoute: typeof AdminReferralsTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/property-matching': {
      id: '/admin/property-matching'
      path: '/property-matching'
      fullPath: '/admin/property-matching'
      preLoaderRoute: typeof AdminPropertyMatchingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plots': {
      id: '/admin/plots'
      path: '/plots'
      fullPath: '/admin/plots'
      preLoaderRoute: typeof AdminPlotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meetings': {
      id: '/admin/meetings'
      path: '/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminMeetingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/installments': {
      id: '/admin/installments'
      path: '/installments'
      fullPath: '/admin/installments'
      preLoaderRoute: typeof AdminInstallmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/goals': {
      id: '/admin/goals'
      path: '/goals'
      fullPath: '/admin/goals'
      preLoaderRoute: typeof AdminGoalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/field-mode': {
      id: '/admin/field-mode'
      path: '/field-mode'
      fullPath: '/admin/field-mode'
      preLoaderRoute: typeof AdminFieldModeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-governance': {
      id: '/admin/data-governance'
      path: '/data-governance'
      fullPath: '/admin/data-governance'
      preLoaderRoute: typeof AdminDataGovernanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/document/receipt/$id': {
      id: '/document/receipt/$id'
      path: '/document/receipt/$id'
      fullPath: '/document/receipt/$id'
      preLoaderRoute: typeof DocumentReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/offer/$id': {
      id: '/document/offer/$id'
      path: '/document/offer/$id'
      fullPath: '/document/offer/$id'
      preLoaderRoute: typeof DocumentOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/agreement/$id': {
      id: '/document/agreement/$id'
      path: '/document/agreement/$id'
      fullPath: '/document/agreement/$id'
      preLoaderRoute: typeof DocumentAgreementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plots/$plotId': {
      id: '/admin/plots/$plotId'
      path: '/$plotId'
      fullPath: '/admin/plots/$plotId'
      preLoaderRoute: typeof AdminPlotsPlotIdRouteImport
      parentRoute: typeof AdminPlotsRoute
    }
  }
}

interface AdminPlotsRouteChildren {
  AdminPlotsPlotIdRoute: typeof AdminPlotsPlotIdRoute
}

const AdminPlotsRouteChildren: AdminPlotsRouteChildren = {
  AdminPlotsPlotIdRoute: AdminPlotsPlotIdRoute,
}

const AdminPlotsRouteWithChildren = AdminPlotsRoute._addFileChildren(
  AdminPlotsRouteChildren,
)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminDataGovernanceRoute: typeof AdminDataGovernanceRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFieldModeRoute: typeof AdminFieldModeRoute
  AdminGoalsRoute: typeof AdminGoalsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminInstallmentsRoute: typeof AdminInstallmentsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMeetingsRoute: typeof AdminMeetingsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlotsRoute: typeof AdminPlotsRouteWithChildren
  AdminPropertyMatchingRoute: typeof AdminPropertyMatchingRoute
  AdminReferralsTestimonialsRoute: typeof AdminReferralsTestimonialsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminTelephonyRoute: typeof AdminTelephonyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminDataGovernanceRoute: AdminDataGovernanceRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFieldModeRoute: AdminFieldModeRoute,
  AdminGoalsRoute: AdminGoalsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminInstallmentsRoute: AdminInstallmentsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMeetingsRoute: AdminMeetingsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlotsRoute: AdminPlotsRouteWithChildren,
  AdminPropertyMatchingRoute: AdminPropertyMatchingRoute,
  AdminReferralsTestimonialsRoute: AdminReferralsTestimonialsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminTelephonyRoute: AdminTelephonyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookVisitRoute: BookVisitRoute,
  ContactRoute: ContactRoute,
  DiasporaRoute: DiasporaRoute,
  InquireRoute: InquireRoute,
  LocationsRoute: LocationsRoute,
  PartnerRoute: PartnerRoute,
  PaymentRoute: PaymentRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  BlogSlugRoute: BlogSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  DocumentAgreementIdRoute: DocumentAgreementIdRoute,
  DocumentOfferIdRoute: DocumentOfferIdRoute,
  DocumentReceiptIdRoute: DocumentReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
